# Generated by Django 4.1.4 on 2022-12-14 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
